spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    schema: classpath:/db/schema-h2.sql
    data: classpath:/db/data-h2.sql
#    url: jdbc:h2:mem:db
#    username: sa
#    password: sa
#    initialize: true
#    type: com.zaxxer.hikari.HikariDataSource
#  h2:
#    console:
#      enabled: true
#      path: /console
mybatis-plus:
#  mapper-locations: classpath:/mapper/*Mapper.xml
  type-enums-package: com.doyutu.springbootmybatis.domain.enums
  type-aliases-package: com.doyutu.springbootmybatis.domain
  global-config:
    db-column-underline: true
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    refresh-mapper: true
#    logic-delete-value: 0
#    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

server:
  port: 8888