spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes:
      properties:
          path:
            logs: ./elasticsearch/log #elasticsearch日志存储目录
            data: ./elasticsearch/data #elasticsearch数据存储目录