spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  application:
    name: SpringBoot-aop
  output:
    ansi:
      enabled: detect
server:
  tomcat:
    uri-encoding: utf-8
    max-threads: 100
    max-connections: 300
  use-forward-headers: true
---
spring:
  profiles: dev
server:
  port: 8081
logging:
  config: classpath:log4j2-spring.xml
  level:
    root: info
---
spring:
  profiles: prod
server:
  port: 8888
logging:
  config: classpath:log4j2-spring.xml
  level:
    root: warn